name: Build & Sign Android App

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
    - uses: gradle/actions/setup-gradle@v4
    - name: Build & Sign
      run: |
        ./gradlew assembleRelease bundleRelease
        # Sign files using r0adkll/sign-android-release
        # See documentation for full configuration details
    - name: Upload Signed Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: Signed-Binaries
        path: |
          app/build/outputs/apk/release/*.apk
          app/build/outputs/bundle/release/*.aab